version: '3.3'
services:

  dftw:
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
    command:
      - /bin/bash
    volumes:
      - ../../:/app/
    stdin_open: true # docker run -i
    tty: true        # docker run -t
