version: '3.3'
services:

  dftw:
    container_name: dftw
    build:
      context: ../../
      dockerfile: ./docker/dftimewolf-release/Dockerfile
    platform: linux/amd64
    environment:
      - DFTIMEWOLF_NO_CURSES=1
    entrypoint:
      - /docker-entrypoint.sh
    volumes:
      - ../../:/app/
    stdin_open: true # docker run -i
    tty: true        # docker run -t
