"""Tests for the ContainerManager."""

import logging
import unittest
from unittest import mock

import pandas as pd

from dftimewolf.lib.containers import containers
from dftimewolf.lib.containers import interface
from dftimewolf.lib.containers import manager


# Test recipe layout, for visual ease.
#
# Preflights:
#           Preflight1
#              |------------------------------------
#              |                 |                 |
#           Preflight2_1      Preflight2_2         |
#                                                  |
# Main Modules:                                    |
#           ModuleB           ModuleC           ModuleA
#      --------|                 |                 |
#      |       |------------------                 |
#      |    ModuleD                                |
#      |       |                                   |
#      --------|------------------------------------
#           ModuleE
#

_TEST_RECIPE = {
  'preflights': [
    {
      'name': 'Preflight1',
      'wants': []
    },
    {
      'name': 'Preflight2',
      'runtime_name': 'Preflight2_1',
      'wants': ['Preflight1']
    },
    {
      'name': 'Preflight2',
      'runtime_name': 'Preflight2_2',
      'wants': ['Preflight1']
    }
  ],
  'modules': [
    {
      'name': 'ModuleA',
      'wants': ['Preflight1']
    },
    {
      'name': 'ModuleB',
      'wants': []
    },
    {
      'name': 'ModuleC',
      'wants': []
    },
    {
      'name': 'ModuleD',
      'wants': ['ModuleB', 'ModuleC']
    },
    {
      'name': 'ModuleE',
      'wants': ['ModuleA', 'ModuleB', 'ModuleD']
    }
  ]
}


class _TestContainer1(interface.AttributeContainer):
  """A Test container."""
  CONTAINER_TYPE = 'test1'

  def __init__(self, param: str):
    super().__init__()
    self.param = param


class _TestContainer2(_TestContainer1):
  """A Test container."""
  CONTAINER_TYPE = 'test2'


class _TestContainer3(interface.AttributeContainer):
  """A Test container."""
  CONTAINER_TYPE = 'test3'

  def __init__(self, field: str):
    super().__init__()
    self.field = field


class ContainerManagerTest(unittest.TestCase):
  """Tests for the ContainerManager."""

  def _CompleteRecipe(self):
    """Marks all the modules as completed."""
    for k in self._container_manager._modules.keys():
      self._container_manager.CompleteModule(k)

  def setUp(self):
    """Set up."""
    super().setUp()

    null_logger = logging.Logger('null')
    null_logger.addHandler(logging.NullHandler())

    self._container_manager = manager.ContainerManager(null_logger)

  def test_GetWithoutRecipeParsed(self):
    """Tests an error is thrown getting containers before a recipe is parsed."""
    with self.assertRaisesRegex(
        RuntimeError, "Container manager has not parsed a recipe yet"):
      self._container_manager.GetContainers('test_module', containers.File)

  def test_StoreWithoutRecipeParsed(self):
    """Tests an error is thrown storing containers before a recipe is parsed."""
    with self.assertRaisesRegex(
        RuntimeError, "Container manager has not parsed a recipe yet"):
      self._container_manager.StoreContainer('test_module',
                                             containers.File('foo', 'foo'))

  def test_ContainerVisibility(self):
    """Tests correct delivery from generating to consuming modules."""
    self._container_manager.ParseRecipe(_TEST_RECIPE)

    # Have every module store a unique container
    for c in (_TEST_RECIPE.get('preflights', []) +
              _TEST_RECIPE.get('modules', [])):
      name = c.get('runtime_name', c['name'])
      self._container_manager.StoreContainer(
        source_module=name, container=_TestContainer1(f'Stored by {name}'))

    with self.subTest('Preflight1'):
      # Only the container generated by itself
      actual = self._container_manager.GetContainers(
          requesting_module='Preflight1', container_class=_TestContainer1)
      self.assertEqual(len(actual), 1)
      self.assertIn(_TestContainer1('Stored by Preflight1'), actual)
      self.assertNotIn(_TestContainer1('Stored by Preflight2_1'), actual)
      self.assertNotIn(_TestContainer1('Stored by Preflight2_2'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleA'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleB'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleC'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleD'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleE'), actual)

    with self.subTest('Preflight2_1'):
      # The container from itself, and Preflight1
      actual = self._container_manager.GetContainers(
          requesting_module='Preflight2_1', container_class=_TestContainer1)
      self.assertEqual(len(actual), 2)
      self.assertIn(_TestContainer1('Stored by Preflight1'), actual)
      self.assertIn(_TestContainer1('Stored by Preflight2_1'), actual)
      self.assertNotIn(_TestContainer1('Stored by Preflight2_2'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleA'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleB'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleC'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleD'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleE'), actual)

    with self.subTest('Preflight2_2'):
      # The container from itself, and Preflight1
      actual = self._container_manager.GetContainers(
          requesting_module='Preflight2_2', container_class=_TestContainer1)
      self.assertEqual(len(actual), 2)
      self.assertIn(_TestContainer1('Stored by Preflight1'), actual)
      self.assertNotIn(_TestContainer1('Stored by Preflight2_1'), actual)
      self.assertIn(_TestContainer1('Stored by Preflight2_2'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleA'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleB'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleC'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleD'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleE'), actual)

    with self.subTest('ModuleA'):
      # The container from itself, and Preflight1
      actual = self._container_manager.GetContainers(
          requesting_module='ModuleA', container_class=_TestContainer1)
      self.assertEqual(len(actual), 2)
      self.assertIn(_TestContainer1('Stored by Preflight1'), actual)
      self.assertNotIn(_TestContainer1('Stored by Preflight2_1'), actual)
      self.assertNotIn(_TestContainer1('Stored by Preflight2_2'), actual)
      self.assertIn(_TestContainer1('Stored by ModuleA'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleB'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleC'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleD'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleE'), actual)

    with self.subTest('ModuleB'):
      # The container from itself only
      actual = self._container_manager.GetContainers(
          requesting_module='ModuleB', container_class=_TestContainer1)
      self.assertEqual(len(actual), 1)
      self.assertNotIn(_TestContainer1('Stored by Preflight1'), actual)
      self.assertNotIn(_TestContainer1('Stored by Preflight2_1'), actual)
      self.assertNotIn(_TestContainer1('Stored by Preflight2_2'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleA'), actual)
      self.assertIn(_TestContainer1('Stored by ModuleB'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleC'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleD'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleE'), actual)

    with self.subTest('ModuleC'):
      # The container from itself only
      actual = self._container_manager.GetContainers(
          requesting_module='ModuleC', container_class=_TestContainer1)
      self.assertEqual(len(actual), 1)
      self.assertNotIn(_TestContainer1('Stored by Preflight1'), actual)
      self.assertNotIn(_TestContainer1('Stored by Preflight2_1'), actual)
      self.assertNotIn(_TestContainer1('Stored by Preflight2_2'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleA'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleB'), actual)
      self.assertIn(_TestContainer1('Stored by ModuleC'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleD'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleE'), actual)

    with self.subTest('ModuleD'):
      # The container from itself, Modules B and C
      actual = self._container_manager.GetContainers(
          requesting_module='ModuleD', container_class=_TestContainer1)
      self.assertEqual(len(actual), 3)
      self.assertNotIn(_TestContainer1('Stored by Preflight1'), actual)
      self.assertNotIn(_TestContainer1('Stored by Preflight2_1'), actual)
      self.assertNotIn(_TestContainer1('Stored by Preflight2_2'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleA'), actual)
      self.assertIn(_TestContainer1('Stored by ModuleB'), actual)
      self.assertIn(_TestContainer1('Stored by ModuleC'), actual)
      self.assertIn(_TestContainer1('Stored by ModuleD'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleE'), actual)

    with self.subTest('ModuleE'):
      # The container from itself, Modules A, B and D
      actual = self._container_manager.GetContainers(
          requesting_module='ModuleE', container_class=_TestContainer1)
      self.assertEqual(len(actual), 4)
      self.assertNotIn(_TestContainer1('Stored by Preflight1'), actual)
      self.assertNotIn(_TestContainer1('Stored by Preflight2_1'), actual)
      self.assertNotIn(_TestContainer1('Stored by Preflight2_2'), actual)
      self.assertIn(_TestContainer1('Stored by ModuleA'), actual)
      self.assertIn(_TestContainer1('Stored by ModuleB'), actual)
      self.assertNotIn(_TestContainer1('Stored by ModuleC'), actual)
      self.assertIn(_TestContainer1('Stored by ModuleD'), actual)
      self.assertIn(_TestContainer1('Stored by ModuleE'), actual)

  def test_MultipleContainerTypes(self):
    """Tests that when a generator stores multiple container types, only the
    requested are returned.
    """
    self._container_manager.ParseRecipe(_TEST_RECIPE)

    self._container_manager.StoreContainer(
        source_module='Preflight1', container=_TestContainer1('param1'))
    self._container_manager.StoreContainer(
        source_module='Preflight1', container=_TestContainer2('param2'))

    actual_tc1 = self._container_manager.GetContainers(
        requesting_module='ModuleA', container_class=_TestContainer1)
    actual_tc2 = self._container_manager.GetContainers(
        requesting_module='ModuleA', container_class=_TestContainer2)

    self.assertEqual(len(actual_tc1), 1)
    self.assertEqual(len(actual_tc2), 1)

    self.assertIn(_TestContainer1('param1'), actual_tc1)
    self.assertIn(_TestContainer2('param2'), actual_tc2)

  def test_MetadataFilter(self):
    """Tests that metdata filters correctly filter containers returned."""
    self._container_manager.ParseRecipe(_TEST_RECIPE)
    c1 = _TestContainer1('param1')
    c2 = _TestContainer1('param2')
    c3 = _TestContainer1('param3')
    c4 = _TestContainer1('param4')

    c1.SetMetadata('Key_1', 'Value_1')
    c2.SetMetadata('Key_1', 'Value_2')
    c3.SetMetadata('Key_2', 'Value_1')
    c4.SetMetadata('Key_2', 'Value_1')

    self._container_manager.StoreContainer(
        source_module='Preflight1', container=c1)
    self._container_manager.StoreContainer(
        source_module='Preflight1', container=c2)
    self._container_manager.StoreContainer(
        source_module='Preflight1', container=c3)
    self._container_manager.StoreContainer(
        source_module='Preflight1', container=c4)

    with self.subTest('No metadata filter'):
      actual = self._container_manager.GetContainers(
          requesting_module='ModuleA', container_class=_TestContainer1)
      self.assertEqual(len(actual), 4)
      self.assertIn(_TestContainer1('param1'), actual)
      self.assertIn(_TestContainer1('param2'), actual)
      self.assertIn(_TestContainer1('param3'), actual)
      self.assertIn(_TestContainer1('param4'), actual)

    with self.subTest('No matching key'):
      actual = self._container_manager.GetContainers(
          requesting_module='ModuleA',
          container_class=_TestContainer1,
          metadata_filter_key='no_matching_key',
          metadata_filter_value='Value_1')
      self.assertEqual(len(actual), 0)

    with self.subTest('No matching value'):
      actual = self._container_manager.GetContainers(
          requesting_module='ModuleA',
          container_class=_TestContainer1,
          metadata_filter_key='Key_1',
          metadata_filter_value='no_matching_value')
      self.assertEqual(len(actual), 0)

    with self.subTest('key_1_value_1'):
      actual = self._container_manager.GetContainers(
          requesting_module='ModuleA',
          container_class=_TestContainer1,
          metadata_filter_key='Key_1',
          metadata_filter_value='Value_1')
      self.assertEqual(len(actual), 1)
      self.assertIn(_TestContainer1('param1'), actual)

    with self.subTest('key_2_value_1'):
      actual = self._container_manager.GetContainers(
          requesting_module='ModuleA',
          container_class=_TestContainer1,
          metadata_filter_key='Key_2',
          metadata_filter_value='Value_1')
      self.assertEqual(len(actual), 2)
      self.assertIn(_TestContainer1('param3'), actual)
      self.assertIn(_TestContainer1('param4'), actual)

  def test_MetadataFilterErrors(self):
    """Tests error modes using metadata filters on retrieval."""
    self._container_manager.ParseRecipe(_TEST_RECIPE)
    c = _TestContainer1('param1')
    c.SetMetadata('key', 'value')

    self._container_manager.StoreContainer(
        source_module='Preflight1', container=c)

    with self.subTest('No key'):
      with self.assertRaisesRegex(
          RuntimeError, 'Must specify both key and value for attribute filter'):
        self._container_manager.GetContainers(
          requesting_module='ModuleA',
          container_class=_TestContainer1,
          metadata_filter_key=None,
          metadata_filter_value='value')

    with self.subTest('No value'):
      with self.assertRaisesRegex(
          RuntimeError, 'Must specify both key and value for attribute filter'):
        self._container_manager.GetContainers(
          requesting_module='ModuleA',
          container_class=_TestContainer1,
          metadata_filter_key='key')

  def test_MarkCompletion(self):
    """Tests container cleanup when marking modules as completed."""
    self._container_manager.ParseRecipe(_TEST_RECIPE)

    # Have every module store a unique container
    for c in (_TEST_RECIPE.get('preflights', []) +
              _TEST_RECIPE.get('modules', [])):
      name = c.get('runtime_name', c['name'])
      self._container_manager.StoreContainer(
          source_module=name, container=_TestContainer1(f'Stored by {name}'))

    with self.subTest('Preflight1'):
      # Delivers to self, Preflight2_1, Preflight2_2 and ModuleA
      self._container_manager.CompleteModule('Preflight1')

      actual = self._container_manager.GetContainers(
          requesting_module='Preflight1', container_class=_TestContainer1)
      self.assertEqual(0, len(actual))

      actual = self._container_manager.GetContainers(
          requesting_module='Preflight2_1', container_class=_TestContainer1)
      self.assertIn(_TestContainer1('Stored by Preflight1'), actual)

      actual = self._container_manager.GetContainers(
          requesting_module='Preflight2_2', container_class=_TestContainer1)
      self.assertIn(_TestContainer1('Stored by Preflight1'), actual)

      actual = self._container_manager.GetContainers(
          requesting_module='ModuleA', container_class=_TestContainer1)
      self.assertIn(_TestContainer1('Stored by Preflight1'), actual)

    with self.subTest('Preflight2_1'):
      # Delivers to self
      self._container_manager.CompleteModule('Preflight2_1')

      actual = self._container_manager.GetContainers(
          requesting_module='Preflight2_1', container_class=_TestContainer1)
      self.assertEqual(0, len(actual))

    with self.subTest('Preflight2_2'):
      # Delvers to self
      self._container_manager.CompleteModule('Preflight2_2')

      actual = self._container_manager.GetContainers(
          requesting_module='Preflight2_1', container_class=_TestContainer1)
      self.assertEqual(0, len(actual))

    with self.subTest('ModuleA'):
      # Delivers to self, ModuleE
      self._container_manager.CompleteModule('ModuleA')

      actual = self._container_manager.GetContainers(
          requesting_module='ModuleA', container_class=_TestContainer1)
      self.assertEqual(0, len(actual))

      actual = self._container_manager.GetContainers(
          requesting_module='ModuleE', container_class=_TestContainer1)
      self.assertIn(_TestContainer1('Stored by ModuleA'), actual)

    with self.subTest('ModuleB'):
      # Delivers to self, ModuleD, ModuleE
      self._container_manager.CompleteModule('ModuleB')

      actual = self._container_manager.GetContainers(
          requesting_module='ModuleB', container_class=_TestContainer1)
      self.assertEqual(0, len(actual))

      actual = self._container_manager.GetContainers(
          requesting_module='ModuleD', container_class=_TestContainer1)
      self.assertIn(_TestContainer1('Stored by ModuleB'), actual)

      actual = self._container_manager.GetContainers(
          requesting_module='ModuleE', container_class=_TestContainer1)
      self.assertIn(_TestContainer1('Stored by ModuleB'), actual)

    with self.subTest('ModuleC'):
      # Delivers to self, ModuleD
      self._container_manager.CompleteModule('ModuleC')

      actual = self._container_manager.GetContainers(
          requesting_module='ModuleC', container_class=_TestContainer1)
      self.assertEqual(0, len(actual))

      actual = self._container_manager.GetContainers(
          requesting_module='ModuleD', container_class=_TestContainer1)
      self.assertIn(_TestContainer1('Stored by ModuleC'), actual)

    with self.subTest('ModuleD'):
      # Delivers to self, ModuleE
      self._container_manager.CompleteModule('ModuleD')

      actual = self._container_manager.GetContainers(
          requesting_module='ModuleD', container_class=_TestContainer1)
      self.assertEqual(0, len(actual))

      actual = self._container_manager.GetContainers(
          requesting_module='ModuleE', container_class=_TestContainer1)
      self.assertIn(_TestContainer1('Stored by ModuleD'), actual)

    with self.subTest('ModuleE'):
      # Delivers to self
      self._container_manager.CompleteModule('ModuleE')

      actual = self._container_manager.GetContainers(
          requesting_module='ModuleE', container_class=_TestContainer1)
      self.assertEqual(0, len(actual))

  def test_PopContainers(self):
    """Tests GetContainers with pop=True."""
    self._container_manager.ParseRecipe(_TEST_RECIPE)

    # Store some containers as prep
    self._container_manager.StoreContainer(
        source_module='Preflight1',
        container=_TestContainer1('Stored by Preflight1'))
    self._container_manager.StoreContainer(
        source_module='ModuleA',
        container=_TestContainer2('Stored by ModuleA'))
    self._container_manager.StoreContainer(
        source_module='ModuleA',
        container=_TestContainer3('Stored by ModuleA'))

    with self.subTest('wrong_source'):
      for _ in range(0, 5):
        # "pop" should be ignored when the requesting module is not the one that
        # stored the container.
        actual = self._container_manager.GetContainers(
            requesting_module='ModuleA',
            container_class=_TestContainer1,
            pop=True)
        self.assertEqual(len(actual), 1)
        self.assertIn(_TestContainer1('Stored by Preflight1'), actual)

    with self.subTest('same_source'):
      actual = self._container_manager.GetContainers(
          requesting_module='ModuleA',
          container_class=_TestContainer2,
          pop=True)
      self.assertEqual(len(actual), 1)
      self.assertIn(_TestContainer2('Stored by ModuleA'), actual)

      # subsequent call returns nothing
      actual = self._container_manager.GetContainers(
          requesting_module='ModuleA',
          container_class=_TestContainer2,
          pop=True)
      self.assertEqual(len(actual), 0)

      # Other containers unaffected
      actual = self._container_manager.GetContainers(
          requesting_module='ModuleA',
          container_class=_TestContainer1)
      self.assertEqual(len(actual), 1)
      self.assertIn(_TestContainer1('Stored by Preflight1'), actual)

      actual = self._container_manager.GetContainers(
          requesting_module='ModuleA',
          container_class=_TestContainer3)
      self.assertEqual(len(actual), 1)
      self.assertIn(_TestContainer3('Stored by ModuleA'), actual)

    with self.subTest('downstream'):
      # If a container pops a module it stored, downstream containers should not
      # be able to receive that container.
      # Have ModuleA and ModuleD store a container. ModuleA pops theirs. ModuleE
      # should only get the one stored by ModuleD
      self._container_manager.StoreContainer(
        source_module='ModuleA',
        container=_TestContainer1('Stored by ModuleA'))
      self._container_manager.StoreContainer(
        source_module='ModuleD',
        container=_TestContainer1('Stored by ModuleD'))
      self._container_manager.GetContainers(
          requesting_module='ModuleA',
          container_class=_TestContainer1,
          pop=True)

      actual = self._container_manager.GetContainers(
          requesting_module='ModuleE',
          container_class=_TestContainer1)
      self.assertEqual(len(actual), 1)
      self.assertIn(_TestContainer1('Stored by ModuleD'), actual)

  def test_StoreDuplicateContainers(self):
    """Tests that attempts to store duplicate containers are disregarded."""
    self._container_manager.ParseRecipe(_TEST_RECIPE)

    self._container_manager.StoreContainer(
        source_module='Preflight1', container=_TestContainer1('param1'))
    self._container_manager.StoreContainer(
        source_module='Preflight1', container=_TestContainer1('param1'))
    self._container_manager.StoreContainer(
        source_module='Preflight1', container=_TestContainer2('param1'))
    self._container_manager.StoreContainer(
        source_module='Preflight1', container=_TestContainer2('param1'))
    self._container_manager.StoreContainer(
        source_module='Preflight1', container=_TestContainer2('param2'))

    # Metadata is not considered in duplicate comparison
    c5 = _TestContainer3('param1')
    c6 = _TestContainer3('param1')
    c5.SetMetadata('key', 'foo')
    c6.SetMetadata('key', 'bar')
    self._container_manager.StoreContainer(
        source_module='Preflight1', container=c5)
    self._container_manager.StoreContainer(
        source_module='Preflight1', container=c6)

    # Dataframe members of containers have special handling; check that too
    df1 = pd.DataFrame(columns=['a', 'b'], data=[[1, 2], [3, 4]])
    df2 = pd.DataFrame(columns=['a', 'b'], data=[[1, 2], [3, 4]])
    df3 = pd.DataFrame(columns=['c', 'd'], data=[[5, 6], [7, 8]])
    self._container_manager.StoreContainer(
        source_module='Preflight1',
        container=containers.DataFrame(
            data_frame=df1, description='Description', name='name'))
    self._container_manager.StoreContainer(
        source_module='Preflight1',
        container=containers.DataFrame(
            data_frame=df2, description='Description', name='name'))
    self._container_manager.StoreContainer(
        source_module='Preflight1',
        container=containers.DataFrame(
            data_frame=df3, description='Description', name='name'))

    actual = self._container_manager.GetContainers(
        requesting_module='ModuleA', container_class=_TestContainer1)
    self.assertEqual(len(actual), 1)
    self.assertIn(_TestContainer1('param1'), actual)

    actual = self._container_manager.GetContainers(
        requesting_module='ModuleA', container_class=_TestContainer2)
    self.assertEqual(len(actual), 2)
    self.assertIn(_TestContainer2('param1'), actual)
    self.assertIn(_TestContainer2('param2'), actual)

    actual = self._container_manager.GetContainers(
        requesting_module='ModuleA', container_class=_TestContainer3)
    self.assertEqual(len(actual), 1)
    self.assertIn(_TestContainer3('param1'), actual)

    actual = self._container_manager.GetContainers(
        requesting_module='ModuleA', container_class=containers.DataFrame)
    self.assertEqual(len(actual), 2)
    self.assertIn(containers.DataFrame(
        data_frame=df1, description='Description', name='name'), actual)
    self.assertIn(containers.DataFrame(
        data_frame=df3, description='Description', name='name'), actual)

  def test_ContainerStreaming(self):
    """Tests that container streaming operates as expected."""
    # Preflight1 will generate containers
    # Preflight2_1 sets up a callback for _TestContainer1 (mock_callback_1)
    # Preflight2_2 sets up a callback for _TestContainer1 (mock_callback_2) and
    #   _TestContainer2 (mock_callback_3)
    # ModuleC sets up a callback for _TestContainer1 (mock_callback_4) which is
    #   not used because no dependency exists
    mock_callback_1 = mock.MagicMock()
    mock_callback_2 = mock.MagicMock()
    mock_callback_3 = mock.MagicMock()
    mock_callback_4 = mock.MagicMock()

    self._container_manager.ParseRecipe(_TEST_RECIPE)

    self._container_manager.RegisterStreamingCallback(
        module_name='Preflight2_1',
        container_type=_TestContainer1,
        callback=mock_callback_1)
    self._container_manager.RegisterStreamingCallback(
        module_name='Preflight2_2',
        container_type=_TestContainer1,
        callback=mock_callback_2)
    self._container_manager.RegisterStreamingCallback(
        module_name='Preflight2_2',
        container_type=_TestContainer2,
        callback=mock_callback_3)
    self._container_manager.RegisterStreamingCallback(
        module_name='ModuleC',
        container_type=_TestContainer1,
        callback=mock_callback_4)

    # These should result in callbacks being executed
    self._container_manager.StoreContainer(
        source_module='Preflight1',
        container=_TestContainer1('From Preflight1'))
    self._container_manager.StoreContainer(
        source_module='Preflight1',
        container=_TestContainer2('From Preflight1'))
    # No callback call - from a non-dependant module
    self._container_manager.StoreContainer(
        source_module='ModuleB', container=_TestContainer1('From ModuleC'))
    # No callback call - Wrong container type
    self._container_manager.StoreContainer(
        source_module='Preflight1',
        container=_TestContainer3('From Preflight1'))

    # Because they were streamed, GetContainers should return nothing.
    actual = self._container_manager.GetContainers(
        requesting_module='Preflight2_1', container_class=_TestContainer1)
    self.assertEqual(len(actual), 0)
    actual = self._container_manager.GetContainers(
        requesting_module='Preflight2_2', container_class=_TestContainer1)
    self.assertEqual(len(actual), 0)
    actual = self._container_manager.GetContainers(
        requesting_module='Preflight2_2', container_class=_TestContainer2)
    self.assertEqual(len(actual), 0)

    # No callback registered by Preflight2_2 for _TestContainer3
    actual = self._container_manager.GetContainers(
        requesting_module='Preflight2_2', container_class=_TestContainer3)
    self.assertEqual(len(actual), 1)
    self.assertEqual(actual[0], _TestContainer3('From Preflight1'))

    # Complete processing (and therefore wait for callbacks to finish)
    self._CompleteRecipe()

    mock_callback_1.assert_called_once_with(_TestContainer1('From Preflight1'))
    mock_callback_2.assert_called_once_with(_TestContainer1('From Preflight1'))
    mock_callback_3.assert_called_once_with(_TestContainer2('From Preflight1'))
    mock_callback_4.assert_not_called()

  def test_SelfStreamContainer(self):
    """A modules streaming callback does not invoke the callback recursively."""
    mock_callback = mock.MagicMock()

    self._container_manager.ParseRecipe(_TEST_RECIPE)

    self._container_manager.RegisterStreamingCallback(
        module_name='Preflight1',
        container_type=_TestContainer1,
        callback=mock_callback)

    self._container_manager.StoreContainer(
        source_module='Preflight1',
        container=_TestContainer1('From Preflight1'))

    mock_callback.assert_not_called()

    # A module can still GetContainers stored by itself though
    actual = self._container_manager.GetContainers(
        requesting_module='Preflight1', container_class=_TestContainer1)
    self.assertEqual(len(actual), 1)
    self.assertEqual(actual[0], _TestContainer1('From Preflight1'))

  def test_ForSelfOnlyStoreContainer(self):
    """Tests the for_self_only param of container storage."""
    self._container_manager.ParseRecipe(_TEST_RECIPE)

    # Register a streaming callback that will only get called once
    mock_callback = mock.MagicMock()
    self._container_manager.RegisterStreamingCallback(
        module_name='Preflight2_1',
        container_type=_TestContainer1,
        callback=mock_callback)

    # Store two containers of the same type, one with for_self_only=True
    self._container_manager.StoreContainer(
        source_module='Preflight1',
        container=_TestContainer1('for_self_only=False'),
        for_self_only=False)
    self._container_manager.StoreContainer(
        source_module='Preflight1',
        container=_TestContainer1('for_self_only=True'),
        for_self_only=True)

    # Check callback
    self.assertEqual(mock_callback.call_count, 1)
    mock_callback.assert_called_once_with(
        _TestContainer1('for_self_only=False'))

    # The same module can retrieve both
    actual = self._container_manager.GetContainers(
        requesting_module='Preflight1',
        container_class=_TestContainer1)

    self.assertEqual(len(actual), 2)
    self.assertIn(_TestContainer1('for_self_only=False'), actual)
    self.assertIn(_TestContainer1('for_self_only=True'), actual)

    # A dependant module can only retrieve the one
    actual = self._container_manager.GetContainers(
        requesting_module='ModuleA',
        container_class=_TestContainer1)

    self.assertEqual(len(actual), 1)
    self.assertIn(_TestContainer1('for_self_only=False'), actual)
    self.assertNotIn(_TestContainer1('for_self_only=True'), actual)

  def test_CallbackErrorReporting(self):
    """Tests that an error in a callback is correctly reported."""
    mock_logger_error = mock.MagicMock()
    mock_callback = mock.MagicMock()
    mock_callback.side_effect = RuntimeError('Test Exception')

    self._container_manager._logger.error = mock_logger_error

    self._container_manager.ParseRecipe(_TEST_RECIPE)

    # Register the callback
    self._container_manager.RegisterStreamingCallback(
        module_name='Preflight2_1',
        container_type=_TestContainer1,
        callback=mock_callback)

    # Fire the callback
    self._container_manager.StoreContainer(
        source_module='Preflight1',
        container=_TestContainer1('From Preflight1'))
    
    # Complete processing (and therefore wait for callbacks to finish)
    self._CompleteRecipe()

    # Was the message logged?
    mock_logger_error.assert_called_once_with('Callback %s encountered error: %s',
                                              str(mock_callback),
                                              'Test Exception',
                                              exc_info=True)


if __name__ == '__main__':
  unittest.main()
