# -*- coding: utf-8 -*-
"""Export processing results to Timesketch."""

from __future__ import unicode_literals

import syslog

from dftimewolf.lib import timesketch_utils
from dftimewolf.lib.module import BaseModule

class TimesketchExporter(BaseModule):
  """Exports a given set of plaso or CSV files to Timesketch.

  input: A list of paths to plaso or CSV files.
  output: A URL to the generated timeline.
  """

  def __init__(self, state):
    super(TimesketchExporter, self).__init__(state)
    self.timesketch_api = None
    self.incident_id = None
    self.sketch_id = None

  def setup(self, # pylint: disable=arguments-differ
            endpoint=None,
            username=None,
            password=None,
            incident_id=None,
            sketch_id=None):
    """Setup a connection to a Timesketch server and create a sketch if needed.

    Args:
      endpoint: str, Timesketch endpoint (e.g. http://timesketch.com/)
      username: str, Username to authenticate against the Timesketch endpoint.
      password: str, Password to authenticate against the Timesketch endpoint.
      incident_id: str, Incident ID or reference. Used in sketch description.
      sketch_id: int, Sketch ID to add the resulting timeline to. If not
          provided, a new sketch is created.
    """
    self.timesketch_api = timesketch_utils.TimesketchApiClient(
        endpoint, username, password)
    self.incident_id = None
    self.sketch_id = int(sketch_id) if sketch_id else None

    # Check that we have a timesketch session
    if not self.timesketch_api.session:
      message = 'Could not connect to Timesketch server at ' + endpoint
      self.state.add_error(message, critical=True)
      return

    if not self.sketch_id:  # No sketch id is provided, create it
      if incident_id:
        sketch_name = 'Sketch for incident ID: ' + incident_id
      else:
        sketch_name = 'Untitled sketch'
      sketch_description = 'Sketch generated by dfTimewolf'

      self.sketch_id = self.timesketch_api.create_sketch(
          sketch_name, sketch_description)
      message = 'Sketch {0:d} created'.format(self.sketch_id)
      print message
      syslog.syslog(message)

  def cleanup(self):
    pass

  def process(self):
    """Executes a Timesketch export."""
    # This is not the best way of catching errors, but timesketch_utils will be
    # deprecated soon.
    # TODO: Consider using the official Timesketch python API.
    if not self.timesketch_api.session:
      message = 'Could not connect to Timesketch server'
      self.state.add_error(message, critical=True)

    named_timelines = []
    for path in self.state.input:
      named_timelines.append(('untitled timeline for '+path, path))
    print "Timesketch exporting"
    print named_timelines
    print self.sketch_id
    self.timesketch_api.export_artifacts(named_timelines, self.sketch_id)
    sketch_url = self.timesketch_api.get_sketch_url(self.sketch_id)
    self.state.output = 'Your Timesketch URL is: {0:s}'.format(sketch_url)
