version: '3.3'
services:

  dftw:
    build:
      context: ../../
      dockerfile: ./docker/dftimewolf-dev/Dockerfile
    entrypoint:
      - /docker-entrypoint.sh
    command: ['envshell']
    volumes:
      - ../../:/app/
    stdin_open: true # docker run -i
    tty: true        # docker run -t
