name: Publish documentation to GitHub Pages

permissions: write-all

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install mkdocs & deps
        run: |
          sudo apt install graphviz
          pip install poetry
          poetry install
      - name: Generate recipe doc
        run: poetry run python docs/generate_recipe_doc.py data/recipes docs
      - name: Build doc
        run: poetry run mkdocs gh-deploy --force
