name: Publish docs to GitHub Pages

permissions: write-all

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install mkdocs & deps
        run: pipenv install --dev
      - name: Generate recipe doc
        run: pipenv run python docs/generate_recipe_doc.py data/recipes
      - name: Build doc
        run: mkdocs build
      - run: mkdocs gh-deploy --force
